### ISSUE TITLE
Quality plan ver 1.1

### ISSUE THREAD

**Issue by jessicakjellin** [OSSQA-PUM/OSSQA#109]

**Comment by Max-Randow** [comment]
Tycker det ser bra ut! Lite fundersam på om vi ska ha 5 sidor med bilder på våra frågor till sprint introspektive bara

**Comment by jessicakjellin** [comment]
jag tycker vi kan ha kvar de, det är ändå bara en appendix

**Comment by grufe** [comment]
Ser bra ut!
Granskad med mindre justeringar i stavning och grammatik.

En mindre kommentar för avsnitt 3.1 Processinledning:
Bör det beskrivas hur uppgiften hamnar i backlog?

**Comment by edvgi966** [comment]
Kommentarer:
- Tror vi ska räkna denna version som 2.0
- En referens till PEP8 och/eller Pylint hade varit bra
Annars ser det väldigt bra ut

**Comment by jessicakjellin** [comment]
flyttar till Done
