### ISSUE TITLE
Revise Project Plan post Seminar 2

### ISSUE THREAD

**Issue by edvgi966** [OSSQA-PUM/OSSQA#113]

**Comment by grufe** [comment]
Ser bra ut!

Granskad med små ändringar i stavning och grammatik.

Inga övriga kommentarer.

**Comment by jessicakjellin** [comment]
review started!

**Comment by jessicakjellin** [comment]
fixat lite grammatik, tagit bort definition av CC och använt ordet kopia istället, tagit bort överflödiga kuriva ord. jag tycker den är klar nu!
