### ISSUE TITLE
Revise Test Plan post Seminar 2

### ISSUE THREAD

**Issue by parslie** [OSSQA-PUM/OSSQA#114]
**Checklist for what areas need to be included:**
- [X] Overview of system modules that are to be tested
- [X] Overview of functions, properties, and metrics that are to be tested
- [x] Overview of test levels and test types
- [x] Description of tools that are used for writing, executing, and viewing tests
- [x] Description of automation of testing
- [x] Description of what is done under one test period (and how long a test period is)
- [x] Description of how failed test cases are managed
- [x] List of test cases (includes connections to requirements)

**Comment by parslie** [comment]
I think the test plan is done now. There are some todo comments in the LaTeX code, however.

**Comment by KarlssonPaGolvet** [comment]
Comments: Fix the definition list, after that I am ready to pass the review. Otherwise, it is clear, easy to read and well written. Good job!

**Comment by grufe** [comment]
Review finished. Looks very good!

Small change done in chapter "Syfte". See history in Overleaf.

**Comment by parslie** [comment]
I have fixed the missing definitions! Will check "syfte" when I get home.

**Comment by parslie** [comment]
The changes to "Syfte" looks good, @grufe. I've also added a reference to fun-coverage now, @KarlssonPaGolvet.
