### ISSUE TITLE
Revise Architechture Document post Seminar 2

### ISSUE THREAD

**Issue by Bacilika** [OSSQA-PUM/OSSQA#117]

**Comment by Bacilika** [comment]
https://www.overleaf.com/project/65b7ac221282cae345f94e01

**Comment by Max-Randow** [comment]
jag kollar

**Comment by Max-Randow** [comment]
Jag har kollat klart. Tyckte det såg bra ut inget som sakas. Fixade stavfel och skrev om lite meningar som använde ord som inte finns.

**Comment by edvgi966** [comment]
Starting Review

**Comment by edvgi966** [comment]
Ändrade versionen till 1.0, några saknande kommatecken, några stavfel annars bra!

**Comment by grufe** [comment]
Granskad med några ändringar.

Det finns en kommentar i overleaf som borde ses över. Handlar om en punktlista som kanske borde stå i löpnade text - Se gärna över den.

Ser annars bra ut!

**Comment by grufe** [comment]
Försökte också fixa så att figurerna och referenslistan hamnade på bra ställen.
