### ISSUE TITLE
perform experiment on larger dependency sample

### ISSUE THREAD

**Issue by KarlssonPaGolvet** [OSSQA-PUM/OSSQA#119]
Perform an experiment on a larger scale and bigger sample of dependencies within SBOM. Check time per SBOM.

**Comment by KarlssonPaGolvet** [comment]
Experiment report is available in Google Drive at this link: https://docs.google.com/document/d/180XvFvLjbmqN5GLMUafwAEBNnUNezmPxT4-tP6hI5Fk/edit?pli=1

**Comment by Max-Randow** [comment]
Ser bra ut. Väldigt detaljerad, men kan vara bra att förklara vad en token är? Typ så man vet varför vi gör experimentet eller vad konsumtion av flera tokens innebär, om ni inte redan har skrivit det någon annan stans.

**Comment by KarlssonPaGolvet** [comment]
Dina kommentarer är lösta med hjälp av en kort definitionslista. Du får gärna kolla igen om du tycker att det ser bra ut

**Comment by edvgi966** [comment]
Starting Review

**Comment by edvgi966** [comment]
Review finished, Ser väldigt bra ut, är lättläst och med relevanta slutsatser, tycker verkligen om definitionslista.(Pass)
