### ISSUE TITLE
Overall code check

### ISSUE THREAD

**Issue by KarlssonPaGolvet** [OSSQA-PUM/OSSQA#125]
Sanity check for code base is needed.

**TODO:**
- Remove file res.json
- Check for prints that shouldbe removed
- Check so Dcostrings are correct
- Change name in the file of example-SBOM to example-SBOM. Now we just borrow another SBOM's name
- lint everything

**Comment by Bacilika** [comment]
TODO: 

- Remove start_ossqa_cmd.sh
