### ISSUE TITLE
Experiment with execution time of SBOM analysis

### ISSUE THREAD

**Issue by edvgi966** [OSSQA-PUM/OSSQA#13]
Reqs R25 and R26

Experiment with and document performance of running a analysis of an sbom
[Experiment 1](https://docs.google.com/document/d/1YsT2hmMHrqJJNvGBsk5HXGgGAG39O1I88tFmBgort5c/edit?usp=sharing)

**Comment by grufe** [comment]
Experiment done. Please Review the produced document linked in this issues description!

**Comment by edvgi966** [comment]
Experiment has been executed and has been documented
