### ISSUE TITLE
Implement functionality for FrontEndAPI

### ISSUE THREAD

**Issue by edvgi966** [OSSQA-PUM/OSSQA#139]
- [ ] Input User Requirments
- [ ] Input Path to SBOM
- [ ] Create UserRequirements
- [ ] Create SBOM class
- [ ] Create callback
- [ ] Call SBOMProcessor to analyse SBOM
- [ ] Call SBOMProcessor to fetch old SBOM by name
- [ ] Call SBOMProcessor to fetch all SBOMs stored in database
Branch from unstable dev and use the UML digram for reference

**Comment by grufe** [comment]
This task has been started, but linting is needed
