### ISSUE TITLE
Create a development overview

### ISSUE THREAD

**Issue by edvgi966** [OSSQA-PUM/OSSQA#14]
Associated with requirement R28

Add a [program flow diagram](https://drive.google.com/file/d/1RfBvWymb5VGLDQN5uVmz3w53ZRuDMGJo/view?usp=drive_link)

Add kanban cards that describe the constuction of the product 

- #22 
- #23 
- #24
- #25 
- #26 
- #27 
- #28 
- #29 
- #30 
- #31

**Comment by KarlssonPaGolvet** [comment]
Review started

**Comment by KarlssonPaGolvet** [comment]
Reviewed, pass

**Comment by KarlssonPaGolvet** [comment]
One more reviewer

**Comment by edvgi966** [comment]
Review started

**Comment by edvgi966** [comment]
#23 references requirement R31 but should be R30, after correction, Pass.

**Comment by jakob123100** [comment]
#23 Requirement number changed from R31 ( wrong req number ) to R30 ( Programkoden skall vara modulär )
