### ISSUE TITLE
Implement functionality of Dependency Grader

### ISSUE THREAD

**Issue by edvgi966** [OSSQA-PUM/OSSQA#141]
- [x] Input list of dependencies and UserRequirements
- [x] Apply UserRequirements to dependencies and return the list

Branch from unstable dev and use the UML digram for reference

**Note: Formerly FinalScoreCalculator**

**Comment by KarlssonPaGolvet** [comment]
Currently working on this on branch test_result_presentation

**Comment by KarlssonPaGolvet** [comment]
All functionality is there, but code needs cleaning, and tests will be written before PR is made

**Comment by KarlssonPaGolvet** [comment]
Update:

All functionality is finished, only tests left to be made before PR is created
