### ISSUE TITLE
Projectplan: split Scrum into Sprint and Scrum

### ISSUE THREAD

**Issue by edvgi966** [OSSQA-PUM/OSSQA#15]
Reqs R8
As we intend to evaluate and improve the sprint process this needs to be more thoroughly described.

**Comment by grufe** [comment]
Section 5.4 about Sprints could be separated into more paragraphs for easier reading,

Otherwise it looks good.

The document now also includes some comments in certain sections. Look at the comments in overleaf and please address these comments.

**Comment by KarlssonPaGolvet** [comment]
Review started

**Comment by KarlssonPaGolvet** [comment]
Looks good. One comment about the documents, see comment in Overleaf. Otherwise, everything seems good acording to me
