### ISSUE TITLE
Requirement Specification - Hand-in Ready Version

### ISSUE THREAD

**Issue by KarlssonPaGolvet** [OSSQA-PUM/OSSQA#32]

**Comment by KarlssonPaGolvet** [comment]
Version ready for hand-in on Monday

**Comment by grufe** [comment]
Review started

**Comment by grufe** [comment]
Review complete. Added some comments in Overleaf. Please look over them.

**Comment by grufe** [comment]
Need 1 more reviewer please!

**Comment by jessicakjellin** [comment]
Review started

**Comment by edvgi966** [comment]
Minor errors within the document that have been commented, but looks right about ready after those have been resolved.
