### ISSUE TITLE
Define Data Flow

### ISSUE THREAD

**Issue by grufe** [OSSQA-PUM/OSSQA#36]
We should create a diagram of the data flow of the program.

This diagram can be detailed. For example include types for parameters of a function.

Discuss which type of diagram this should be.

**Comment by edvgi966** [comment]
[Link](https://drive.google.com/file/d/1dqVUM3AVnW6FHIFDjiYer6jtSFiDiRxx/view?usp=sharing)

**Comment by parslie** [comment]
Reviewed: It looks good. What module handles which data in what way is clear. No further comments.
