### ISSUE TITLE
Test plan - Make features to be tested and test items consistent with other documents

### ISSUE THREAD

**Issue by parslie** [OSSQA-PUM/OSSQA#44]
The sections that have been changed are the sections about **test items (testobjekt)**, **features to be tested (funktionalitet som kommer testas)**, **features not to be tested (funktionalitet som inte kommer testas)**, and **defintions (definitioner)**.

**Comment by parslie** [comment]
Ready to be reviewed!

**Comment by KarlssonPaGolvet** [comment]
Review started

**Comment by KarlssonPaGolvet** [comment]
Review done. Everything looks good

**Comment by jessicakjellin** [comment]
review started

**Comment by jessicakjellin** [comment]
review done, looks good!! added two comments but we can discuss them, otherwise this document is done! ⭐
