### ISSUE TITLE
Test Plan, v 0.1

### ISSUE THREAD

**Issue by grufe** [OSSQA-PUM/OSSQA#5]

**Comment by Max-Randow** [comment]
Har översatt allting till svenska, kolla gärna igenom för att göra ev ändring om det finns bättre ord på rubrikerna.

**Comment by jessicakjellin** [comment]
Changed small stuff in accordance to standards (english words italicized etc.), one comment about adding projectplan to a bibliography like other documents, otherwise it looks good!! :D

**Comment by KarlssonPaGolvet** [comment]
Review started

**Comment by KarlssonPaGolvet** [comment]
Reviewed, one comment, otherwise, looks good!

Recommend to make references at the bottom using bibLatex like the other documents

**Comment by KarlssonPaGolvet** [comment]
Reviewed, one comment, otherwise, looks good!

Recommend to make references at the bottom using bibLatex like the other documenta
