### ISSUE TITLE
Requirement Specification supplement

### ISSUE THREAD

**Issue by KarlssonPaGolvet** [OSSQA-PUM/OSSQA#60]
Fixing Requirement Specification after superviser's review

**Comment by KarlssonPaGolvet** [comment]
Ready for review

**Comment by parslie** [comment]
Review started!

**Comment by parslie** [comment]
Overall it looks very good. I feel a little clarification that "användarens preferenser" is referring to the user's priorities would be good. Otherwise lines like "ger ett läsbart resultat i enlighet med användarens preferenser" could be interpreted as referring to the formatting of the result.

**Comment by Bacilika** [comment]
Looks Good. Feel free to merge!
