### ISSUE TITLE
Quality Plan supplement

### ISSUE THREAD

**Issue by grufe** [OSSQA-PUM/OSSQA#61]

**Comment by KarlssonPaGolvet** [comment]
Review started

**Comment by KarlssonPaGolvet** [comment]
Review done. One comment regarding documents:

Sounds like the docments are fully within the LIPS templates, but since review a lot has changed and it doesn't conform to these any more.

Otherwise, looks great! Apart from this little comment, ready for habnd-in according to me ^^

**Comment by edvgi966** [comment]
See comments in overleaf, other than that looks really good!

**Comment by parslie** [comment]
I started reviewing this yesterday, but didn't finish it then. Now I have, and I see nothing to comment on other than what has already been commented on. It looks good!
