### ISSUE TITLE
Evaluation of Period

### ISSUE THREAD

**Issue by edvgi966** [OSSQA-PUM/OSSQA#88]
This issue is related to document hand-in 2 which describes a need for a documenting on goal completion.

**Comment by KarlssonPaGolvet** [comment]
Review started

**Comment by KarlssonPaGolvet** [comment]
Review done. Looks good!

**Comment by jessicakjellin** [comment]
review started

**Comment by jessicakjellin** [comment]
review done, looks good!

**Comment by grufe** [comment]
Review done, some edits made!
